import { UserAccount, OperationalGroup, SubOperationalGroup, Checklist, ChecklistItem, DayOperationalData } from '@/types/aviation';

export const DEFAULT_USERS: UserAccount[] = [
  {
    uNumber: 'admin',
    name: 'Chief Ops Administrator',
    role: 'ADMIN',
    passwordHash: 'Admin220!',
    mustChangePassword: false,
    department: 'Ground Operations Management',
    createdDate: '2026-01-01T00:00:00.000Z',
  },
  {
    uNumber: 'supervisor',
    name: 'Duty Supervisor',
    role: 'SUPERVISOR',
    passwordHash: 'Supervisor220!',
    mustChangePassword: false,
    department: 'Airside Ramp Supervision',
    createdDate: '2026-01-01T00:00:00.000Z',
  },
  {
    uNumber: 'U194283',
    name: 'RAKESH PARMAR',
    role: 'USER',
    passwordHash: 'U194283',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U194317',
    name: 'JASPREET MALIK',
    role: 'USER',
    passwordHash: 'U194317',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U137790',
    name: 'DANISH MANZOOR',
    role: 'USER',
    passwordHash: 'U137790',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U148038',
    name: 'PRIYANKA JAIN',
    role: 'USER',
    passwordHash: 'U148038',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U152260',
    name: 'MANISH PARMAR',
    role: 'USER',
    passwordHash: 'U152260',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U128206',
    name: 'ADITI BHALLA',
    role: 'USER',
    passwordHash: 'U128206',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U177834',
    name: 'CHRISTY',
    role: 'USER',
    passwordHash: 'U177834',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U151236',
    name: 'ARUN SINGH',
    role: 'USER',
    passwordHash: 'U151236',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U193966',
    name: 'ANKITA DUTTA',
    role: 'USER',
    passwordHash: 'U193966',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U148685',
    name: 'ANKIT MISHRA',
    role: 'USER',
    passwordHash: 'U148685',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U177840',
    name: 'BHAGWATI BISWAKARMA',
    role: 'USER',
    passwordHash: 'U177840',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U141960',
    name: 'HARPREET SINGH',
    role: 'USER',
    passwordHash: 'U141960',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U152261',
    name: 'RONAK SINGH',
    role: 'USER',
    passwordHash: 'U152261',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U148030',
    name: 'SIMARPREET KAUR',
    role: 'USER',
    passwordHash: 'U148030',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U125316',
    name: 'ABHAY TIWARI',
    role: 'USER',
    passwordHash: 'U125316',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U184279',
    name: 'YASIR BHAT',
    role: 'USER',
    passwordHash: 'U184279',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U152267',
    name: 'VAIBHAV',
    role: 'USER',
    passwordHash: 'U152267',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U161306',
    name: 'PRAVEEN BALIYAN',
    role: 'USER',
    passwordHash: 'U161306',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U148697',
    name: 'ISHA MANSURI',
    role: 'USER',
    passwordHash: 'U148697',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U150984',
    name: 'IPSHITA KAUR',
    role: 'USER',
    passwordHash: 'U150984',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U145815',
    name: 'PRACHI',
    role: 'USER',
    passwordHash: 'U145815',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U193961',
    name: 'SIDHI SHARMA',
    role: 'USER',
    passwordHash: 'U193961',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U191790',
    name: 'PAYAL',
    role: 'USER',
    passwordHash: 'U191790',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U115470',
    name: 'KHUSHI',
    role: 'USER',
    passwordHash: 'U115470',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U169709',
    name: 'MALVIKA VYAS',
    role: 'USER',
    passwordHash: 'U169709',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U193967',
    name: 'SHIVANGI',
    role: 'USER',
    passwordHash: 'U193967',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U145816',
    name: 'AASIF ALI',
    role: 'USER',
    passwordHash: 'U145816',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U142564',
    name: 'KASHISH BACHHAS',
    role: 'USER',
    passwordHash: 'U142564',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U115377',
    name: 'VINAY RAWAT',
    role: 'USER',
    passwordHash: 'U115377',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U146671',
    name: 'KAJAL',
    role: 'USER',
    passwordHash: 'U146671',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U145823',
    name: 'MANJEET KAUR',
    role: 'USER',
    passwordHash: 'U145823',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U142565',
    name: 'SIMARJEET KAUR',
    role: 'USER',
    passwordHash: 'U142565',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U143324',
    name: 'KRITIKA SHARMA',
    role: 'USER',
    passwordHash: 'U143324',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U146675',
    name: 'KANIKA MEHTA',
    role: 'USER',
    passwordHash: 'U146675',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U119170',
    name: 'MAYANK AGGARWAL',
    role: 'USER',
    passwordHash: 'U119170',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U124807',
    name: 'AMIT KUMAR',
    role: 'USER',
    passwordHash: 'U124807',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U154745',
    name: 'SHIVAM KUMAR',
    role: 'USER',
    passwordHash: 'U154745',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U103735',
    name: 'SUJATA BHARTI',
    role: 'USER',
    passwordHash: 'U103735',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U146554',
    name: 'MAYANK BANGARI',
    role: 'USER',
    passwordHash: 'U146554',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U146557',
    name: 'SHUBHAM PRASAD',
    role: 'USER',
    passwordHash: 'U146557',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U149989',
    name: 'VARUN SHARMA',
    role: 'USER',
    passwordHash: 'U149989',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U193964',
    name: 'PREETI',
    role: 'USER',
    passwordHash: 'U193964',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U102164',
    name: 'DAVINDER SINGH',
    role: 'USER',
    passwordHash: 'U102164',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U102841',
    name: 'PAWANPREET',
    role: 'USER',
    passwordHash: 'U102841',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U152823',
    name: 'AYUSH MEHRA',
    role: 'USER',
    passwordHash: 'U152823',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U149994',
    name: 'SHUBHAM KESTWAL',
    role: 'USER',
    passwordHash: 'U149994',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  },
  {
    uNumber: 'U155961',
    name: 'SUDIP KUMAR',
    role: 'USER',
    passwordHash: 'U155961',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  }

,
  {
    uNumber: 'U123456',
    name: 'U123456',
    role: 'USER',
    passwordHash: 'U123456',
    mustChangePassword: false,
    department: 'Ground Operations',
    createdDate: new Date().toISOString(),
    isAuthorized: true,
  }
];

export const FLIGHT_CODES = ['LX147', 'LX2647', 'LH763', 'LH761'] as const;

// Helper to create checklist items with isMandatory=true by default
export function makeItem(id: string, seq: number, text: string, isMandatory: boolean = true): ChecklistItem {
  return {
    id,
    sequenceOrder: seq,
    text,
    isMandatory,
    status: 'not_done',
  };
}

// Master Flight Sub-groups - Returns empty array (sample sub-groups removed)
export function getMasterFlightSubGroups(_prefix: string): SubOperationalGroup[] {
  return [];
}

// Non-flight operational groups - Clean default groups with no pre-populated sample sub-groups
export function getNonFlightGroups(): OperationalGroup[] {
  return [
    {
      id: 'grp-arrivals',
      name: 'Arrivals Terminal Operations',
      code: 'ARR-OPS',
      isFlightGroup: false,
      isMandatory: true,
      isVerified: false,
      subGroups: [],
    },
    {
      id: 'grp-departures',
      name: 'Departures & Gate Management',
      code: 'DEP-OPS',
      isFlightGroup: false,
      isMandatory: true,
      isVerified: false,
      subGroups: [],
    },
    {
      id: 'grp-sbd',
      name: 'SBD Operations (Self Bag Drop)',
      code: 'SBD-OPS',
      isFlightGroup: false,
      isMandatory: true,
      isVerified: false,
      subGroups: [],
    },
    {
      id: 'grp-security',
      name: 'Security & Airside Access',
      code: 'SEC-OPS',
      isFlightGroup: false,
      isMandatory: true,
      isVerified: false,
      subGroups: [],
    },
    {
      id: 'grp-day-shift',
      name: 'Day Shift Operations',
      code: 'DAY-OPS',
      isFlightGroup: false,
      isMandatory: true,
      isVerified: false,
      subGroups: [],
    },
  ];
}

const SAMPLE_SUBGROUP_NAMES = new Set([
  'pre-arrival & ramp safety',
  'turnaround, cargo & baggage handling',
  'cabin servicing, catering & fueling',
  'pre-departure, loadsheet & pushback clearance',
  'baggage reclaim hall & belts',
  'customs & transfer corridors',
  'boarding gate infrastructure',
  'kiosk & scale health check',
  'perimeter & ramp badge control',
]);

// Helper to strip any legacy sample sub-groups from day data
export function cleanSampleSubGroups(groups: OperationalGroup[]): OperationalGroup[] {
  if (!groups || !Array.isArray(groups)) return [];
  return groups.map((g) => ({
    ...g,
    subGroups: (g.subGroups || []).filter((sub) => {
      const nameLower = sub.name.trim().toLowerCase();
      if (SAMPLE_SUBGROUP_NAMES.has(nameLower)) return false;
      if (
        sub.id.includes('-sub-pre-arrival') ||
        sub.id.includes('-sub-turnaround-cargo') ||
        sub.id.includes('-sub-cabin-catering') ||
        sub.id.includes('-sub-pre-departure') ||
        sub.id === 'arr-sub-baggage-hall' ||
        sub.id === 'arr-sub-customs-transit' ||
        sub.id === 'dep-sub-gate-ops' ||
        sub.id === 'sbd-sub-kiosk-maintenance' ||
        sub.id === 'sec-sub-perimeter'
      ) {
        return false;
      }
      return true;
    }),
  }));
}

// Generate complete default groups for a target date
export function generateDefaultGroups(): OperationalGroup[] {
  const flightGroups: OperationalGroup[] = FLIGHT_CODES.map((code) => {
    return {
      id: `grp-${code.toLowerCase()}`,
      name: `Flight ${code}`,
      code: code,
      isFlightGroup: true,
      isMandatory: true,
      isVerified: false,
      subGroups: getMasterFlightSubGroups(`flt-${code.toLowerCase()}`),
    };
  });

  const nonFlightGroups = getNonFlightGroups();

  return [...flightGroups, ...nonFlightGroups];
}

export function createInitialDayData(dateStr: string): DayOperationalData {
  return {
    date: dateStr,
    groups: generateDefaultGroups(),
    isShiftClosed: false,
    lastUpdated: `${dateStr}T00:00:00.000Z`,
  };
}
